---
name: "Refresh docs build dependencies"
"on":
  schedule:
    # Weekly
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      base-branch:
        required: false
        type: string
      pr-branch:
        required: false
        type: string

jobs:
  refresh:
    uses: ./.github/workflows/reusable-pip-compile.yml
    with:
      message: "ci: refresh docs build dependencies"
      base-branch: "${{ inputs.base-branch || 'devel' }}"
      pr-branch: "${{ inputs.pr-branch || 'pip-compile/devel/docs' }}"
      nox-args: -e pip-compile-3.10(requirements)
      changed-files: "tests/*.txt"
